# Generated by Django 3.1.5 on 2021-01-10 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='listMapper',
            new_name='listobj',
        ),
    ]
