# Generated by Django 3.1.5 on 2021-01-10 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20210110_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='listobj',
            new_name='list',
        ),
    ]
