# Generated by Django 3.1.5 on 2021-02-12 09:11

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20210114_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('duedate', models.CharField(max_length=30)),
                ('activity', django_mysql.models.ListCharField(models.CharField(max_length=50), max_length=5000, size=None)),
            ],
        ),
        migrations.RenameField(
            model_name='board',
            old_name='lists',
            new_name='tasks',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='List',
        ),
        migrations.RemoveField(
            model_name='task',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='duedate',
        ),
        migrations.AddField(
            model_name='task',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.board'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='List',
        ),
        migrations.AddField(
            model_name='card',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.task'),
        ),
    ]
